override __ALMKFS_CURRENT_INCLUDE_MAKEFILE := $(realpath $(lastword $(MAKEFILE_LIST)))
override __ALMKFS_CURRENT_INCLUDE_DIRECTORY := $(patsubst %/,%,$(dir $(__ALMKFS_CURRENT_INCLUDE_MAKEFILE)))

ifdef __ALMKFS_INCLUDE_GUARD_INCLUDE
$(if $(filter $(__ALMKFS_INCLUDED_ENTRYPOINT_MAKEFILE),$(__ALMKFS_CURRENT_INCLUDE_MAKEFILE)),,$(error Conflicting almakefiles entrypoints: already loaded $(__ALMKFS_INCLUDED_ENTRYPOINT_MAKEFILE), also got $(__ALMKFS_CURRENT_INCLUDE_MAKEFILE)))
else
override __ALMKFS_INCLUDE_GUARD_INCLUDE = 1
override __ALMKFS_INCLUDED_ENTRYPOINT_MAKEFILE := $(__ALMKFS_CURRENT_INCLUDE_MAKEFILE)
override __ALMKFS_INCLUDED_ENTRYPOINT_DIRECTORY := $(__ALMKFS_CURRENT_INCLUDE_DIRECTORY)

include $(__ALMKFS_INCLUDED_ENTRYPOINT_DIRECTORY)/mk/common.mk
include $(call almkfs-active-module-files,$(__ALMKFS_MODULE_FILES))
endif
