override __ALMAKE_CURRENT_INCLUDE_MAKEFILE := $(realpath $(lastword $(MAKEFILE_LIST)))
override __ALMAKE_CURRENT_INCLUDE_DIRECTORY := $(patsubst %/,%,$(dir $(__ALMAKE_CURRENT_INCLUDE_MAKEFILE)))

ifdef __ALMAKE_INCLUDE_GUARD_INCLUDE
$(if $(filter $(__ALMAKE_INCLUDED_ENTRYPOINT_MAKEFILE),$(__ALMAKE_CURRENT_INCLUDE_MAKEFILE)),,$(error Conflicting almakefiles entrypoints: already loaded $(__ALMAKE_INCLUDED_ENTRYPOINT_MAKEFILE), also got $(__ALMAKE_CURRENT_INCLUDE_MAKEFILE)))
else
override __ALMAKE_INCLUDE_GUARD_INCLUDE = 1
override __ALMAKE_INCLUDED_ENTRYPOINT_MAKEFILE := $(__ALMAKE_CURRENT_INCLUDE_MAKEFILE)
override __ALMAKE_INCLUDED_ENTRYPOINT_DIRECTORY := $(__ALMAKE_CURRENT_INCLUDE_DIRECTORY)

include $(__ALMAKE_INCLUDED_ENTRYPOINT_DIRECTORY)/mk/common.mk
include $(call almake-active-module-files,$(__ALMAKE_MODULE_FILES))
endif
